### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by ilya-moskovtsev**
Task 2 (Serve SPA in AWS)
https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task2-serve-spa-aws/task.md

Manual deploy
S3 bucket
http://ilymos-serverless-deploy.s3-website-us-east-1.amazonaws.com
CloudFront
https://d2hohf69xcv6pq.cloudfront.net

Automated deploy
S3 bucket
http://ilymos-serverless-cloudformation-deploy.s3-website-us-east-1.amazonaws.com
CloudFront
https://dyzw59fxpwli2.cloudfront.net/

### CODE REVIEW

**Comment by SergeyKovalchuk** [comment]
Sorry for confusing description of task2 
Please follow this approach to submit task https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1983994429

**Comment by Emerkof** [comment]
@ilya-moskovtsev Please re-open this MR and make it point to `main` branch of _YOUR PERSONAL_ repo

**Comment by ilya-moskovtsev** [comment]
> Sorry for confusing description of task2
> Please follow this approach to submit task https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1983994429

Sorry, I did not intent to do this.
Here is a correct link.
https://github.com/ilya-moskovtsev/nodejs-aws-fe/pull/1/files

**Comment by ilya-moskovtsev** [comment]
> @ilya-moskovtsev Please, re-open this MR and make it point to `main` branch of _YOUR PERSONAL_ repo

Thank you for pointing out. No idea how this happened)
Here is the correct link.
https://github.com/ilya-moskovtsev/nodejs-aws-fe/pull/1/files

**Pull request closed without merging**
