### PR TITLE
Task 02

### PR DESCRIPTION
**Pull request by numatay**
Closes [task2-serve-spa-aws] (https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task2-serve-spa-aws/task.md)

CloudFront manual website - d5mlahslqo02h.cloudfront.net
CloudFront automated website - d8com57mktn4d.cloudfront.net

image

### CODE REVIEW

**Comment by kalitamih** [comment]
I can't see any content by provided links. Could you add provide me valid links?

**Comment by numatay** [comment]
Hi @kalitamih! Here is the list of links for the task:
Manual deployment
- S3 bucket http://task-02-app-bucket.s3-website-eu-west-1.amazonaws.com/
- CloudFront https://dr4jxru0dsto7.cloudfront.net

Automated deployment
- Cloudfront https://d5bzm0spt9d1j.cloudfront.net/

**Comment by kalitamih** [comment]
> Hi @kalitamih! Here is the list of links for the task:
> Manual deployment
> 
> * S3 bucket http://task-02-app-bucket.s3-website-eu-west-1.amazonaws.com/
> * CloudFront https://dr4jxru0dsto7.cloudfront.net
> 
> Automated deployment
> 
> * Cloudfront https://d5bzm0spt9d1j.cloudfront.net/

This pull request needs to be inside your public repository. Could you do make pull request to your public forked repository in the banch "main"?

**Comment by numatay** [comment]
I have mistakenly chosen the wrong destination branch of the PR. Please refer to https://github.com/numatay/nodejs-aws-fe/pull/1 for evaluating task 02.

**Pull request closed without merging**
